services:
  db:
    image: postgres:15
    container_name: smart_resto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ramituis1
      POSTGRES_DB: smart_resto_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data